# EDA and manipulation of latlongs to work with map polygons using GeoJson and Python

## Import all required libraries and datasets

In [1]:
import pandas as pd
import numpy as np
from turfpy.measurement import boolean_point_in_polygon
from geojson import Point, Polygon, Feature
import tqdm
tqdm.tqdm.pandas()

In [2]:
# 2 datasets: the one from created from the security and the other one from the xls
df4 = pd.read_csv('address_coords.csv', sep = ',')
df4

      Unnamed: 0      LATITUDE     LONGITUDE
0              0  -23,54270055  -46,42492336
1              1           NaN           NaN
2              2           NaN           NaN
3              3  -22,31372181  -49,03168574
4              4             0             0
...          ...           ...           ...
6995        6995           NaN           NaN
6996        6996           NaN           NaN
6997        6997           NaN           NaN
6998        6998  -23,63287867  -46,52286009
6999        6999  -23,56043176  -46,63812323

[7000 rows x 3 columns]

## Transforming columns in record arrays, creating the polygon out of the arrays and boolean point

In [3]:
regioes['NOME']=='Leste'

NameError: name 'regioes' is not defined

In [352]:
# Creating a variable that receives the mask of Leste column, its latitude and longitude and transforms it in a records arrays
rec_array_leste = regioes[regioes['NOME']=='Leste'][['POINT_X', 'POINT_Y']].to_records(index = False).tolist()

In [ ]:
# Creating the polygon of East rec array
pol_rec_array_leste = Polygon([rec_array_leste])

In [ ]:
point = Feature(geometry=Point((-46.42492336, -23.54270055)))
boolean_point_in_polygon(point, pol_rec_array_leste)
point

In [276]:
boolean_point_in_polygon(point, pol_rec_array_leste)

True

In [277]:
regioes['NOME']=='Oeste'

0        False
1        False
2        False
3        False
4        False
         ...
41631    False
41632    False
41633    False
41634    False
41635    False
Name: NOME, Length: 41636, dtype: bool

## Cleaning LATITUDE and LONGITUDE columns

In [4]:
df4 = df4.dropna()
print(df4)

      Unnamed: 0      LATITUDE     LONGITUDE
0              0  -23,54270055  -46,42492336
3              3  -22,31372181  -49,03168574
4              4             0             0
5              5   -23,6236916  -46,50799009
6              6  -23,49096469  -46,38649642
...          ...           ...           ...
6992        6992  -20,56887291  -47,40558592
6993        6993   -23,1916298   -46,8791841
6994        6994  -23,45398249  -46,68080267
6998        6998  -23,63287867  -46,52286009
6999        6999  -23,56043176  -46,63812323

[5852 rows x 3 columns]

In [5]:
df4.shape

(5852, 3)

## Deleting rows that have invalid values for Latitude and Longitude

In [6]:
df4['LATITUDE'].unique()

array(['-23,54270055', '-22,31372181', '0', ..., '-23,45398249',
       '-23,63287867', '-23,56043176'], dtype=object)

In [7]:
zero= df4.loc[df4['LATITUDE'].str.startswith('0')].index
zero

Int64Index([   4,   11,   13,   21,   26,   27,   43,   44,   45,   46,
            ...
            3237, 3282, 3295, 3320, 3329, 3413, 3479, 3561, 3796, 5520],
           dtype='int64', length=546)

In [8]:
df4.drop(zero, inplace=True)
df4

C:\Users\Indra\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

      Unnamed: 0      LATITUDE     LONGITUDE
0              0  -23,54270055  -46,42492336
3              3  -22,31372181  -49,03168574
5              5   -23,6236916  -46,50799009
6              6  -23,49096469  -46,38649642
7              7   -23,5430714  -46,41263264
...          ...           ...           ...
6992        6992  -20,56887291  -47,40558592
6993        6993   -23,1916298   -46,8791841
6994        6994  -23,45398249  -46,68080267
6998        6998  -23,63287867  -46,52286009
6999        6999  -23,56043176  -46,63812323

[5306 rows x 3 columns]

In [9]:
df_reg= df4.loc[df4['LATITUDE'].str.startswith('REGISTRADO')].index
df_reg

Int64Index([3835, 4754, 5602, 5603, 5604, 6487, 6488, 6489], dtype='int64')

In [10]:
df4.drop(df_reg, inplace=True)
df4

C:\Users\Indra\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

      Unnamed: 0      LATITUDE     LONGITUDE
0              0  -23,54270055  -46,42492336
3              3  -22,31372181  -49,03168574
5              5   -23,6236916  -46,50799009
6              6  -23,49096469  -46,38649642
7              7   -23,5430714  -46,41263264
...          ...           ...           ...
6992        6992  -20,56887291  -47,40558592
6993        6993   -23,1916298   -46,8791841
6994        6994  -23,45398249  -46,68080267
6998        6998  -23,63287867  -46,52286009
6999        6999  -23,56043176  -46,63812323

[5298 rows x 3 columns]

In [ ]:
seg_polygon = pd.read_csv('seg_polygon.csv')
seg_polygon

In [12]:
crime = df4.loc[df4['LATITUDE'].str.startswith('CRIME')].index
df4.drop(crime, inplace=True)

C:\Users\Indra\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [13]:
df = pd.read_excel('MDIP_2013_2021.xlsx')
crime = df.loc[df['LATITUDE'].str.startswith('CRIME', '0', 'REG')].index

TypeError: startswith() takes from 2 to 3 positional arguments but 4 were given

In [ ]:
def clean_lat(x):
    if isinstance(x,str):
        if x.startswith('CRIME') or x.startswith('0') or x.startswith('REG'):
             return None
        else:
            return x
    else:
        if x == 0:
            return None
        else:
            return x
        df['LATITUDE'] = df['LATITUDE'].apply(clean_lat)
        df['LONGITUDE'] = df['LONGITUDE'].apply(clean_lat)

In [ ]:
df['LATITUDE'] = df['LATITUDE'].apply(clean_lat)

In [ ]:
df['LONGITUDE'] = df['LONGITUDE'].apply(clean_lat)

In [14]:
df

,CIDADE_ELABORACAO,SEC_ELABORACAO,DEP_ELABORACAO,NUM_BO,ANO_BO,DATA_FATO,dia,mês,ano,MÊS OCOR,...,DESCR_TIPOLOCAL,LOGRADOURO,NUMERO_LOGRADOURO,LATITUDE,LONGITUDE,NATUREZAS,CONDUTA,DESDOBRAMENTO,FLAG_VITIMA_FATAL,DATAHORA_REGISTRO_BO
0,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,2,2013,2013-01-01 00:00:00,1.0,1.0,2013.0,1,...,Via pública,R LUIS MATHEUS,1,-23.542701,-46.424923,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-01 00:00:00
1,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,4,2013,2013-01-01 00:00:00,1.0,1.0,2013.0,1,...,Residência,DA VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,NaN,NaN,NaN,Resistência (art. 329),NaN,NaN,Sim,2013-01-01 00:00:00
2,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,6,2013,2013-01-02 00:00:00,2.0,1.0,2013.0,1,...,Residência,DA VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,NaN,NaN,NaN,Ato Infracional,NaN,NaN,Sim,2013-01-02 00:00:00
3,BAURU,DEL.SEC.BAURU,DEINTER 4 - BAURU,9,2013,2013-01-30 00:00:00,30.0,1.0,2013.0,1,...,Via pública,R SANTA AGUEDA,96,-22.313722,-49.031686,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-31 00:00:00
4,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,9,2013,2013-01-03 00:00:00,3.0,1.0,2013.0,1,...,Via pública,R ORMINDA PINTO VIELA,6,0,0,Resistência (art. 329),NaN,NaN,Sim,2013-01-03 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,ARACATUBA,DEL.SEC.ARACATUBA,DEINTER 10 - ARAÇATUBA,7995,2021,2021-08-30 00:00:00,30.0,8.0,2021.0,8,...,Via Pública,RUA LUIZ PEREIRA BARRETO,76,NaN,NaN,Homicídio simples (art. 121),NaN,Morte decorrente de intervenção Policial,Sim,2021-08-30 00:00:00
6996,GUARULHOS,DEL.SEC.GUARULHOS,DEMACRO,4225,2021,2021-08-31 00:00:00,31.0,8.0,2021.0,8,...,Via Pública,"RUA PÔRTO VELHO,",890,NaN,NaN,Homicídio simples (art. 121),NaN,NaN,Sim,2021-09-01 00:00:00
6997,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,342,2021,2021-08-31 00:00:00,31.0,8.0,2021.0,8,...,Residência,DA VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,NaN,NaN,NaN,Homicídio simples (art. 121),NaN,"Art. 329 - Opor-se à execução de ato legal, me...",Sim,2021-08-31 00:00:00
6998,S.ANDRE,DEL.SEC.SANTO ANDRÉ,DEMACRO,3053,2021,2021-08-31 00:00:00,31.0,8.0,2021.0,8,...,Via pública,RUA OZANAN,27,-23.632879,-46.52286,"Roubo (art. 157), Comunicação de Óbito",OUTROS,NaN,Sim,2021-08-31 00:00:00
6999,S.PAULO,DEL.SEC.1º CENTRO,DECAP,4759,2021,2021-08-31 00:00:00,31.0,8.0,2021.0,8,...,Via pública,AVENIDA DA LIBERDADE,863,-23.560432,-46.638123,Homicídio simples (art. 121),INTERIOR ESTABELECIMENTO,"Art. 157 - Subtrair coisa móvel alheia, para s...",Sim,2021-08-31 00:00:00

In [ ]:
df.drop(crime, inplace=True)

In [122]:
registrado = df4.loc[df4.LATITUDE.str.startswith('REG')]

In [15]:
df4['LATITUDE'].isnull().value_counts()

False    5297
Name: LATITUDE, dtype: int64

## Changing commas to point and transforming values to float

In [16]:
df4 = pd.read_csv('address_coords_limpo.csv')
df4.to_csv('address_coords_limpo.csv', index= False)

In [17]:
df4['LATITUDE'] = df4['LATITUDE'].str.replace(',','.')#.astype(float)
df4['LONGITUDE'] = df4['LONGITUDE'].str.replace(',','.')
df4

<ipython-input-17-ecea5bb77114>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['LATITUDE'] = df4['LATITUDE'].str.replace(',','.')#.astype(float)
<ipython-input-17-ecea5bb77114>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['LONGITUDE'] = df4['LONGITUDE'].str.replace(',','.')

      Unnamed: 0      LATITUDE     LONGITUDE
0              0  -23.54270055  -46.42492336
3              3  -22.31372181  -49.03168574
5              5   -23.6236916  -46.50799009
6              6  -23.49096469  -46.38649642
7              7   -23.5430714  -46.41263264
...          ...           ...           ...
6992        6992  -20.56887291  -47.40558592
6993        6993   -23.1916298   -46.8791841
6994        6994  -23.45398249  -46.68080267
6998        6998  -23.63287867  -46.52286009
6999        6999  -23.56043176  -46.63812323

[5298 rows x 3 columns]

In [127]:
float_leste = df4.loc[0:100].astype(float).apply(regioes_pol, dicio_all = dicio_all, axis = 1)
float_leste

0      Leste
3       None
5      Leste
6      Leste
7      Leste
       ...
95       Sul
96     Oeste
97     Oeste
99     Oeste
100     None
Length: 65, dtype: object

In [140]:
df4 = df4[['LATITUDE', 'LONGITUDE']].astype(float)

In [17]:
df4.dtypes

LATITUDE      float64
LONGITUDE     float64
bairros_sp     object
dtype: object

# Creating a function to convert all regions to a polygon format

In [21]:
regioes['NOME']=='Oeste'
rec_array_oeste = regioes[regioes['NOME']=='Oeste'][['POINT_X', 'POINT_Y']].to_records(index = False).tolist()
pol_rec_array_oeste = Polygon([rec_array_oeste])

NameError: name 'regioes' is not defined

In [22]:
point = Feature(geometry=Point((-46.42492336, -23.54270055)))
boolean_point_in_polygon(point, pol_rec_array_oeste)

NameError: name 'Feature' is not defined

In [144]:
regioes['NOME'].unique()

array(['Leste', 'Norte', 'Sul', 'Oeste', 'Centro'], dtype=object)

In [145]:
dicio_all = {}

for region in regioes['NOME'].unique(): 
    rec_array = regioes[regioes['NOME']== region][['POINT_X', 'POINT_Y']].to_records(index = False).tolist()
    pol_rec_array = Polygon([rec_array])
    dicio_all[region] = pol_rec_array
    
dicio_all.keys()

dict_keys(['Leste', 'Norte', 'Sul', 'Oeste', 'Centro'])

In [147]:
#check every key if the point is inside one of the key values / every pol_rec_array, check if the point is there if so it returns the region's name
def regioes_pol(row, dicio_all):
    point = Feature(geometry=Point((row['LONGITUDE'], row['LATITUDE'])))
    for x in dicio_all:
        if boolean_point_in_polygon(point, dicio_all[x]):
            return x
        else:
            None

In [148]:
df4.apply(regioes_pol, dicio_all = dicio_all, axis=1)

0        Leste
3         None
5        Leste
6        Leste
7        Leste
         ...
6992      None
6993      None
6994     Norte
6998      None
6999    Centro
Length: 5297, dtype: object

In [ ]:
# df4 = df4.drop(columns=['Unnamed: 0'])

# Importing GeoJson to open the dataset with São Paulo city's districts

In [ ]:
import geojson
with open('DISTRITO_MUNICIPAL_SP_SMDUPolygon.json') as f:
    gj = geojson.load(f)['features']
    
def regioes_pol(row, gj):
    point = geojson.Feature(geometry=geojson.Point((row['LONGITUDE'], row['LATITUDE'])))
    for x in gj:
        if boolean_point_in_polygon(point, x):
            return x['properties']
        else:
            None
            
df4['bairros_sp'] = df4.apply(regioes_pol, gj = gj, axis=1)
df4.to_csv('address_coords_limpo.csv', index= False)
df_coords_limpo = pd.read_csv('address_coords_limpo.csv')
df_coords_limpo

In [ ]:
import geojson

In [ ]:
with open('DISTRITO_MUNICIPAL_SP_SMDUPolygon.json') as f:
    gj = geojson.load(f)['features']

In [ ]:
def regioes_pol(row, gj):
    point = geojson.Feature(geometry=geojson.Point((row['LONGITUDE'], row['LATITUDE'])))
    for x in gj:
        if boolean_point_in_polygon(point, x):
            return x['properties']
        else:
            None

In [ ]:
df4['bairros_sp'] = df4.apply(regioes_pol, gj = gj, axis=1)

In [ ]:
df4.to_csv('address_coords_limpo.csv', index= False)

In [ ]:
df4.to_csv('address_coords_limpo.csv', index= False)
df_coords_limpo = pd.read_csv('address_coords_limpo.csv')
df_coords_limpo

In [358]:
df_coords_limpo

       LATITUDE  LONGITUDE                                bairros_sp
0    -23.542701 -46.424923  {'Codigo': 47, 'Nome': 'JOSE BONIFACIO'}
1    -22.313722 -49.031686                                       NaN
2    -23.623692 -46.507990       {'Codigo': 76, 'Nome': 'SAPOPEMBA'}
3    -23.490965 -46.386496  {'Codigo': 36, 'Nome': 'ITAIM PAULISTA'}
4    -23.543071 -46.412633      {'Codigo': 31, 'Nome': 'GUAIANASES'}
...         ...        ...                                       ...
5292 -20.568873 -47.405586                                       NaN
5293 -23.191630 -46.879184                                       NaN
5294 -23.453982 -46.680803     {'Codigo': 11, 'Nome': 'BRASILANDIA'}
5295 -23.632879 -46.522860                                       NaN
5296 -23.560432 -46.638123       {'Codigo': 49, 'Nome': 'LIBERDADE'}

[5297 rows x 3 columns]

# Opening the original dataset and adding the new cleaned polygon columns

In [165]:
df = df.drop(columns=['LATITUDE'])
df = df.drop(columns=['LONGITUDE'])

In [341]:
df_letalidade_sp

,CIDADE_ELABORACAO,SEC_ELABORACAO,DEP_ELABORACAO,NUM_BO,ANO_BO,DATA_FATO,dia,mês,ano,MÊS OCOR,...,LATITUDE_x,LONGITUDE_x,NATUREZAS,CONDUTA,DESDOBRAMENTO,FLAG_VITIMA_FATAL,DATAHORA_REGISTRO_BO,Unnamed: 0,LATITUDE_y,LONGITUDE_y
0,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,2,2013,2013-01-01 00:00:00,1.0,1.0,2013.0,1,...,-23.542701,-46.424923,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-01 00:00:00,0,"-23,54270055","-46,42492336"
3,BAURU,DEL.SEC.BAURU,DEINTER 4 - BAURU,9,2013,2013-01-30 00:00:00,30.0,1.0,2013.0,1,...,-22.313722,-49.031686,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-31 00:00:00,3,"-22,31372181","-49,03168574"
5,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,11,2013,2013-01-03 00:00:00,3.0,1.0,2013.0,1,...,-23.623692,-46.507990,Resistência (art. 329),NaN,NaN,Sim,2013-01-04 00:00:00,5,"-23,6236916","-46,50799009"
6,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,13,2013,2013-01-04 00:00:00,4.0,1.0,2013.0,1,...,-23.490965,-46.386496,Resistência (art. 329),NaN,NaN,Sim,2013-01-04 00:00:00,6,"-23,49096469","-46,38649642"
7,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,15,2013,2013-01-04 00:00:00,4.0,1.0,2013.0,1,...,-23.543071,-46.412633,Ato Infracional,NaN,NaN,Sim,2013-01-05 00:00:00,7,"-23,5430714","-46,41263264"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6992,FRANCA,DEL.SEC.FRANCA,DEINTER 3 - RIBEIRAO PRETO,8074,2021,2021-08-28 00:00:00,28.0,8.0,2021.0,8,...,-20.568873,-47.405586,Homicídio simples (art. 121),NaN,NaN,Sim,2021-08-28 05:37:00,6992,"-20,56887291","-47,40558592"
6993,JUNDIAI,DEL.SEC.JUNDIAI,DEINTER 2 - CAMPINAS,2032,2021,2021-08-29 00:00:00,29.0,8.0,2021.0,8,...,-23.191630,-46.879184,"Homicídio simples (art. 121), Receptação (art....",VEICULO,Lesão corporal decorrente de intervenção polic...,Sim,2021-08-30 00:00:00,6993,"-23,1916298","-46,8791841"
6994,S.PAULO,DEL.SEC.4º NORTE,DECAP,3030,2021,2021-08-30 00:00:00,30.0,8.0,2021.0,8,...,-23.453982,-46.680803,"Roubo (art. 157), Homicídio simples (art. 121)",APLICATIVO DE MOBILIDADE URBANA,§2o.Se a violência ou grave ameaça é exercida ...,Sim,2021-08-30 00:00:00,6994,"-23,45398249","-46,68080267"
6998,S.ANDRE,DEL.SEC.SANTO ANDRÉ,DEMACRO,3053,2021,2021-08-31 00:00:00,31.0,8.0,2021.0,8,...,-23.632879,-46.522860,"Roubo (art. 157), Comunicação de Óbito",OUTROS,NaN,Sim,2021-08-31 00:00:00,6998,"-23,63287867","-46,52286009"
6999,S.PAULO,DEL.SEC.1º CENTRO,DECAP,4759,2021,2021-08-31 00:00:00,31.0,8.0,2021.0,8,...,-23.560432,-46.638123,Homicídio simples (art. 121),INTERIOR ESTABELECIMENTO,"Art. 157 - Subtrair coisa móvel alheia, para s...",Sim,2021-08-31 00:00:00,6999,"-23,56043176","-46,63812323"

In [343]:
df_letalidade_sp = df.merge(df4, left_index= True, right_index = True)
df_letalidade_sp

,CIDADE_ELABORACAO,SEC_ELABORACAO,DEP_ELABORACAO,NUM_BO,ANO_BO,DATA_FATO,dia,mês,ano,MÊS OCOR,...,LATITUDE_x,LONGITUDE_x,NATUREZAS,CONDUTA,DESDOBRAMENTO,FLAG_VITIMA_FATAL,DATAHORA_REGISTRO_BO,Unnamed: 0,LATITUDE_y,LONGITUDE_y
0,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,2,2013,2013-01-01 00:00:00,1.0,1.0,2013.0,1,...,-23.542701,-46.424923,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-01 00:00:00,0,"-23,54270055","-46,42492336"
3,BAURU,DEL.SEC.BAURU,DEINTER 4 - BAURU,9,2013,2013-01-30 00:00:00,30.0,1.0,2013.0,1,...,-22.313722,-49.031686,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-31 00:00:00,3,"-22,31372181","-49,03168574"
5,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,11,2013,2013-01-03 00:00:00,3.0,1.0,2013.0,1,...,-23.623692,-46.507990,Resistência (art. 329),NaN,NaN,Sim,2013-01-04 00:00:00,5,"-23,6236916","-46,50799009"
6,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,13,2013,2013-01-04 00:00:00,4.0,1.0,2013.0,1,...,-23.490965,-46.386496,Resistência (art. 329),NaN,NaN,Sim,2013-01-04 00:00:00,6,"-23,49096469","-46,38649642"
7,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,15,2013,2013-01-04 00:00:00,4.0,1.0,2013.0,1,...,-23.543071,-46.412633,Ato Infracional,NaN,NaN,Sim,2013-01-05 00:00:00,7,"-23,5430714","-46,41263264"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6992,FRANCA,DEL.SEC.FRANCA,DEINTER 3 - RIBEIRAO PRETO,8074,2021,2021-08-28 00:00:00,28.0,8.0,2021.0,8,...,-20.568873,-47.405586,Homicídio simples (art. 121),NaN,NaN,Sim,2021-08-28 05:37:00,6992,"-20,56887291","-47,40558592"
6993,JUNDIAI,DEL.SEC.JUNDIAI,DEINTER 2 - CAMPINAS,2032,2021,2021-08-29 00:00:00,29.0,8.0,2021.0,8,...,-23.191630,-46.879184,"Homicídio simples (art. 121), Receptação (art....",VEICULO,Lesão corporal decorrente de intervenção polic...,Sim,2021-08-30 00:00:00,6993,"-23,1916298","-46,8791841"
6994,S.PAULO,DEL.SEC.4º NORTE,DECAP,3030,2021,2021-08-30 00:00:00,30.0,8.0,2021.0,8,...,-23.453982,-46.680803,"Roubo (art. 157), Homicídio simples (art. 121)",APLICATIVO DE MOBILIDADE URBANA,§2o.Se a violência ou grave ameaça é exercida ...,Sim,2021-08-30 00:00:00,6994,"-23,45398249","-46,68080267"
6998,S.ANDRE,DEL.SEC.SANTO ANDRÉ,DEMACRO,3053,2021,2021-08-31 00:00:00,31.0,8.0,2021.0,8,...,-23.632879,-46.522860,"Roubo (art. 157), Comunicação de Óbito",OUTROS,NaN,Sim,2021-08-31 00:00:00,6998,"-23,63287867","-46,52286009"
6999,S.PAULO,DEL.SEC.1º CENTRO,DECAP,4759,2021,2021-08-31 00:00:00,31.0,8.0,2021.0,8,...,-23.560432,-46.638123,Homicídio simples (art. 121),INTERIOR ESTABELECIMENTO,"Art. 157 - Subtrair coisa móvel alheia, para s...",Sim,2021-08-31 00:00:00,6999,"-23,56043176","-46,63812323"

In [344]:
df_letalidade_sp.to_excel('seg_merge_polygon.xls', index= False)
seg_merge_polygon = pd.read_excel('seg_merge_polygon.xls')
seg_merge_polygon

<ipython-input-344-a4ca1d90287f>:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  df_letalidade_sp.to_excel('seg_merge_polygon.xls', index= False)

,CIDADE_ELABORACAO,SEC_ELABORACAO,DEP_ELABORACAO,NUM_BO,ANO_BO,DATA_FATO,dia,mês,ano,MÊS OCOR,...,LATITUDE_x,LONGITUDE_x,NATUREZAS,CONDUTA,DESDOBRAMENTO,FLAG_VITIMA_FATAL,DATAHORA_REGISTRO_BO,Unnamed: 0,LATITUDE_y,LONGITUDE_y
0,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,2,2013,2013-01-01,1,1,2013,1,...,-23.542701,-46.424923,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-01 00:00:00,0,"-23,54270055","-46,42492336"
1,BAURU,DEL.SEC.BAURU,DEINTER 4 - BAURU,9,2013,2013-01-30,30,1,2013,1,...,-22.313722,-49.031686,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-31 00:00:00,3,"-22,31372181","-49,03168574"
2,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,11,2013,2013-01-03,3,1,2013,1,...,-23.623692,-46.507990,Resistência (art. 329),NaN,NaN,Sim,2013-01-04 00:00:00,5,"-23,6236916","-46,50799009"
3,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,13,2013,2013-01-04,4,1,2013,1,...,-23.490965,-46.386496,Resistência (art. 329),NaN,NaN,Sim,2013-01-04 00:00:00,6,"-23,49096469","-46,38649642"
4,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,15,2013,2013-01-04,4,1,2013,1,...,-23.543071,-46.412633,Ato Infracional,NaN,NaN,Sim,2013-01-05 00:00:00,7,"-23,5430714","-46,41263264"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5292,FRANCA,DEL.SEC.FRANCA,DEINTER 3 - RIBEIRAO PRETO,8074,2021,2021-08-28,28,8,2021,8,...,-20.568873,-47.405586,Homicídio simples (art. 121),NaN,NaN,Sim,2021-08-28 05:37:00,6992,"-20,56887291","-47,40558592"
5293,JUNDIAI,DEL.SEC.JUNDIAI,DEINTER 2 - CAMPINAS,2032,2021,2021-08-29,29,8,2021,8,...,-23.191630,-46.879184,"Homicídio simples (art. 121), Receptação (art....",VEICULO,Lesão corporal decorrente de intervenção polic...,Sim,2021-08-30 00:00:00,6993,"-23,1916298","-46,8791841"
5294,S.PAULO,DEL.SEC.4º NORTE,DECAP,3030,2021,2021-08-30,30,8,2021,8,...,-23.453982,-46.680803,"Roubo (art. 157), Homicídio simples (art. 121)",APLICATIVO DE MOBILIDADE URBANA,§2o.Se a violência ou grave ameaça é exercida ...,Sim,2021-08-30 00:00:00,6994,"-23,45398249","-46,68080267"
5295,S.ANDRE,DEL.SEC.SANTO ANDRÉ,DEMACRO,3053,2021,2021-08-31,31,8,2021,8,...,-23.632879,-46.522860,"Roubo (art. 157), Comunicação de Óbito",OUTROS,NaN,Sim,2021-08-31 00:00:00,6998,"-23,63287867","-46,52286009"
5296,S.PAULO,DEL.SEC.1º CENTRO,DECAP,4759,2021,2021-08-31,31,8,2021,8,...,-23.560432,-46.638123,Homicídio simples (art. 121),INTERIOR ESTABELECIMENTO,"Art. 157 - Subtrair coisa móvel alheia, para s...",Sim,2021-08-31 00:00:00,6999,"-23,56043176","-46,63812323"

In [346]:
seg_merge_polygon.columns

Index(['CIDADE_ELABORACAO', 'SEC_ELABORACAO', 'DEP_ELABORACAO', 'NUM_BO',
       'ANO_BO', 'DATA_FATO', 'dia', 'mês', 'ano', 'MÊS OCOR', 'ANO OCOR',
       'DP_ELABORACAO', 'COORPORAÇÃO', 'SITUAÇÃO', 'ID_DELEGACIA',
       'MUNICIPIO_CIRC', 'DEPARTAMENTO_\nCIRC', 'SECCIONAL_CIRC',
       'CIRCUNSCRIÇÃO', 'DESCR_TIPO_PESSOA', 'SEXO_PESSOA', 'IDADE_PESSOA',
       'COR', 'DATA_NASCIMENTO_PESSOA', 'DESCR_PROFISSAO', 'HORA_FATO',
       'DESCR_TIPOLOCAL', 'LOGRADOURO', 'NUMERO_LOGRADOURO', 'LATITUDE_x',
       'LONGITUDE_x', 'NATUREZAS', 'CONDUTA', 'DESDOBRAMENTO',
       'FLAG_VITIMA_FATAL', 'DATAHORA_REGISTRO_BO', 'Unnamed: 0', 'LATITUDE_y',
       'LONGITUDE_y'],
      dtype='object')

In [10]:
seg_merge_polygon['bairros_sp'] = seg_merge_polygon['bairros_sp'].apply(lambda x: x['Nome'] if pd.notnull(x) else None)

NameError: name 'seg_merge_polygon' is not defined

In [240]:
seg_merge_polygon['bairros_sp']

0       JOSE BONIFACIO
1                 None
2            SAPOPEMBA
3       ITAIM PAULISTA
4           GUAIANASES
             ...
5292              None
5293              None
5294       BRASILANDIA
5295              None
5296         LIBERDADE
Name: bairros_sp, Length: 5297, dtype: object

In [241]:
seg_merge_polygon.to_excel('seg_merge_polygon_clean.xls', index= False)

<ipython-input-241-83854a8789ca>:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  seg_merge_polygon.to_excel('seg_merge_polygon_clean.xls', index= False)

In [332]:
seg_merge_polygon_clean = pd.read_excel('seg_merge_polygon_clean.xls')
seg_merge_polygon_clean

,CIDADE_ELABORACAO,SEC_ELABORACAO,DEP_ELABORACAO,NUM_BO,ANO_BO,DATA_FATO,dia,mês,ano,MÊS OCOR,...,LOGRADOURO,NUMERO_LOGRADOURO,NATUREZAS,CONDUTA,DESDOBRAMENTO,FLAG_VITIMA_FATAL,DATAHORA_REGISTRO_BO,LATITUDE,LONGITUDE,bairros_sp
0,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,2,2013,2013-01-01 00:00:00,1.0,1.0,2013.0,1,...,R LUIS MATHEUS,1,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-01 00:00:00,-23.542701,-46.424923,JOSE BONIFACIO
1,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,4,2013,2013-01-01 00:00:00,1.0,1.0,2013.0,1,...,DA VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,NaN,Resistência (art. 329),NaN,NaN,Sim,2013-01-01 00:00:00,-22.313722,-49.031686,NaN
2,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,6,2013,2013-01-02 00:00:00,2.0,1.0,2013.0,1,...,DA VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,NaN,Ato Infracional,NaN,NaN,Sim,2013-01-02 00:00:00,-23.623692,-46.507990,SAPOPEMBA
3,BAURU,DEL.SEC.BAURU,DEINTER 4 - BAURU,9,2013,2013-01-30 00:00:00,30.0,1.0,2013.0,1,...,R SANTA AGUEDA,96,Homicídio simples (art. 121),NaN,NaN,Sim,2013-01-31 00:00:00,-23.490965,-46.386496,ITAIM PAULISTA
4,S.PAULO,DHPP - DEP. HOM. PROTECAO PESSOA,DHPP,9,2013,2013-01-03 00:00:00,3.0,1.0,2013.0,1,...,R ORMINDA PINTO VIELA,6,Resistência (art. 329),NaN,NaN,Sim,2013-01-03 00:00:00,-23.543071,-46.412633,GUAIANASES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5292,SANTOS,DEL.SEC.SANTOS,DEINTER 6 - SANTOS,1203,2019,2019-06-13 00:00:00,13.0,6.0,2019.0,6,...,CAMINHO SÃO JORGE,1,Homicídio simples (art. 121),TRANSEUNTE,Contra autoridade ou agente descrito nos arts....,Sim,2019-06-13 00:00:00,-20.568873,-47.405586,NaN
5293,GUARULHOS,DEL.SEC.GUARULHOS,DEMACRO,1450,2019,2019-06-10 00:00:00,10.0,6.0,2019.0,6,...,RUA JAMIL JOÃO ZARIFE,1000,Homicídio simples (art. 121),ESTABELECIMENTO COMERCIAL,NaN,Sim,2019-06-10 00:00:00,-23.191630,-46.879184,NaN
5294,ITANHAEM,DEL.SEC.ITANHAEM,DEINTER 6 - SANTOS,1498,2019,2019-06-21 00:00:00,21.0,6.0,2019.0,6,...,RUA DO CANO,1500,Drogas sem autorização ou em desacordo (Art.33...,NaN,Lesão corporal decorrente de intervenção polic...,Sim,2019-06-21 00:00:00,-23.453982,-46.680803,BRASILANDIA
5295,S.JOSE DOS CAMPOS,DEL.SEC.S.JOSÉ DOS CAMPOS,DEINTER 1 - SAO JOSE DOS CAMPOS,1583,2019,2019-06-04 00:00:00,4.0,6.0,2019.0,6,...,RUA ANGELO SCARPEL,54,"Homicídio simples (art. 121), Localização/Apre...",VEICULO,"Art. 329 - Opor-se à execução de ato legal, me...",Sim,2019-06-05 00:00:00,-23.632879,-46.522860,NaN
5296,MIRASSOL,DEL.SEC.S.JOSE DO RIO PRETO,DEINTER 5 - SAO JOSE DO RIO PRETO,1612,2019,2019-06-03 00:00:00,3.0,6.0,2019.0,6,...,ESTRADA VICINAL JOÃO JOAQUIM TELES FILHO,1,Homicídio simples (art. 121),NaN,Lesão corporal decorrente de intervenção polic...,Sim,2019-06-03 00:00:00,-23.560432,-46.638123,LIBERDADE

In [334]:
seg_polygon[seg_polygon['SECCIONAL_CIRC'] == 'DEL.SEC.7º ITAQUERA']['bairros_sp'].value_counts().head(40)

NameError: name 'seg_polygon' is not defined

In [258]:
seg_merge_polygon_clean['SECCIONAL_CIRC'].value_counts()

DEL.SEC.3º OESTE                            422
DEL.SEC.7º ITAQUERA                         400
DEL.SEC.4º NORTE                            381
DEL.SEC.8º SAO MATEUS                       381
DEL.SEC.SANTOS                              373
                                           ...
DIVECAR-DIV.INV.S/FURTO,R.R.VEIC.E CARGA      1
REGISTRADO NA PF - BO 1114/16                 1
POLÍCIA FEDERAL Inquérito da PF 1082/14       1
REGISTRADO EM (MG)                            1
REGISTRADO NA PF - BO 206/17                  1
Name: SECCIONAL_CIRC, Length: 76, dtype: int64